### ISSUE TITLE
Link to FAQ page from ABOUT US menu

### ISSUE THREAD

**Issue by leonstafford** [sleepbusorg/sleepbus_org#10]
### Acceptance criteria

- [ ] `Frequently asked questions` link appears as per mockup and links to FAQ page

![faqlink](https://cloud.githubusercontent.com/assets/2066833/26447815/71b9373e-419e-11e7-9b12-552e06ff81b1.png)

**Comment by bakersemail** [comment]
What URL would you like? Is this an existing page already?

**Comment by leonstafford** [comment]
@bakersemail - yes, there is an existing route defined in `config/extended_routes.php` to `/faq`

**Comment by leonstafford** [comment]
This issue was moved to sleepbusorg/sleepbus.org#17
