### ISSUE TITLE
Log out link should be cased

### ISSUE THREAD

**Issue by bakersemail** [sleepbusorg/sleepbus_org#15]
When logged in, the logout link is all lowercase and looks out of place from other links.
Suggest to make it: "Log out" from "logout".

- [x] Log out link to read `Log out`

**Comment by leonstafford** [comment]
Thanks! Good to fix

**Comment by bakersemail** [comment]
Submitted merge request: https://gitlab.com/ljs/sleepbus/merge_requests/1

**Comment by leonstafford** [comment]
This issue was moved to sleepbusorg/sleepbus.org#12
