### ISSUE TITLE
Can't receive emails on local dev environment

### ISSUE THREAD

**Issue by leonstafford** [sleepbusorg/sleepbus_org#7]
### Background

Many emails in the system, so ability to test them locally is much needed.

Something like [MailCatcher](https://mailcatcher.me/) would be great.

### Acceptance criteria

- [x]  Ability to view emails sent out from local dev server to any address

**Comment by leonstafford** [comment]
@bakersemail - would you be able to code-review this one for me?

https://gitlab.com/ljs/sleepbus/commits/catch_local_emails

**Comment by bakersemail** [comment]
I've commented in the last commit. Would you rather the response go here or in gitlab?

**Comment by leonstafford** [comment]
Got it, thanks!

**Comment by leonstafford** [comment]
This issue was moved to sleepbusorg/sleepbus.org#20
